In [12]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from datetime import datetime

pd.set_option('display.max_columns', None)

In [13]:
base = pd.read_excel('ESTUDIANTES.xlsx')

<h1>DATOS ESTUDIANTES</h1>

In [14]:
base.head()

,AGNO_INGRESO,FECHA_INGRESO,FECHA_EGRESO,DOCUMENTO,COD_ESTUDIANTIL,NOMBRE,PROGRAMA,NUM_MATRICULAS,CREDITOS_PENSUM,CREDITOS_APROBADOS,CREDITOS_REPROBADOS,MATERIAS_REPROBADAS,MATERIAS_CANCELADAS,FECHA_NACIMIENTO,GENERO,ESTADO_CIVIL,RELIGION,MUNICIPIO_PROCEDENCIA,DEPTO_PROCEDENCIA,PAIS_PROCEDENCIA,ESTRATO,TRABAJO,TIPO_TRABAJO,RANGO_INGRESOS,DURACION_TRABAJO,ESTADO
0,1997,1997-01-01,2013-01-01,71977148,971008101,CORDOBA DE LA ROSA JAVIER ANDRES,LIC. TEOLOGÍA,10,173,181.0,9,3,0,1969-05-15,MASCULINO,CASADO (A),ADVENTISTA,GRANADA,META,COLOMBIA,ESTRATO 2,NO,[NINGUNO],[NINGUNO],[NINGUNO],GRADUADO
1,1998,1998-02-01,2006-01-01,43621143,982056104,CATAÑO OCAMPO VIVIANA MARÍA,LIC. BÁS. NATURALES,1,164,185.0,9,4,0,1977-01-06,FEMENINO,CASADO (A),ADVENTISTA,CALI,VALLE DEL CAUCA,COLOMBIA,ESTRATO 1,NO,[NINGUNO],[NINGUNO],[NINGUNO],GRADUADO
2,1999,1999-01-01,NaT,28177911,991020214,CUBIDES GERENA BIVIANA,CONTADURÍA PÚBLICA,2,219,75.0,29,14,0,1975-01-08,FEMENINO,SEPARADO (A),ADVENTISTA,CIMITARRA,SANTANDER,COLOMBIA,ESTRATO 1,SÍ,TIEMPO COMPLETO,ENTRE 0 - 1 MÍNIMO,ENTRE 6 MESES - 1 AÑO,INACTIVO
3,2000,2000-01-01,2006-01-01,18009899,201010211,JAMES CUADRADO JOELL ELIECER,TEC. EMPRESARIAL,1,124,129.0,31,9,0,1981-07-03,MASCULINO,SOLTERO (A),ADVENTISTA,ISLA SAN ANDRES,SAN ANDRES,COLOMBIA,ESTRATO 3,NO,[NINGUNO],[NINGUNO],[NINGUNO],GRADUADO
4,2001,2001-01-01,2015-01-01,19599564,211050106,DIAZ MORENO ADOLFO ENRIQUE,LIC. TEOLOGÍA,5,189,196.0,6,3,0,1979-10-05,MASCULINO,CASADO (A),ADVENTISTA,FUNDACION,MAGDALENA,COLOMBIA,ESTRATO 2,SÍ,TIEMPO COMPLETO,ENTRE 2 - 3 MÍNIMOS,MÁS DE 1 AÑO,GRADUADO

In [15]:
base.dtypes

AGNO_INGRESO                      int64
FECHA_INGRESO            datetime64[ns]
FECHA_EGRESO             datetime64[ns]
DOCUMENTO                        object
COD_ESTUDIANTIL                   int64
NOMBRE                           object
PROGRAMA                         object
NUM_MATRICULAS                    int64
CREDITOS_PENSUM                   int64
CREDITOS_APROBADOS              float64
CREDITOS_REPROBADOS               int64
MATERIAS_REPROBADAS               int64
MATERIAS_CANCELADAS               int64
FECHA_NACIMIENTO         datetime64[ns]
GENERO                           object
ESTADO_CIVIL                     object
RELIGION                         object
MUNICIPIO_PROCEDENCIA            object
DEPTO_PROCEDENCIA                object
PAIS_PROCEDENCIA                 object
ESTRATO                          object
TRABAJO                          object
TIPO_TRABAJO                     object
RANGO_INGRESOS                   object
DURACION_TRABAJO                 object
ESTADO                           object
dtype: object